# Generated by Django 4.1.7 on 2023-05-18 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='adress',
            new_name='address',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='fournisseur',
            name='user',
        ),
        migrations.AlterField(
            model_name='commande',
            name='produits',
            field=models.ManyToManyField(related_name='commandes', to='magasin.produit'),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='is_superuser',
            field=models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status'),
        ),
    ]
