# Generated by Django 4.1.7 on 2023-05-18 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('magasin', '0002_rename_adress_fournisseur_address_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fournisseur',
            old_name='address',
            new_name='adress',
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='fournisseur',
            name='is_staff',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='fournisseur',
            name='is_superuser',
            field=models.BooleanField(default=False),
        ),
    ]
